### ISSUE TITLE
Can't view all playlist items

### ISSUE THREAD

**Issue by ImDevinC** [bottiger/SoundWaves#109]
This is on a Pixel XL. I have added two different podcasts (99% Invisible and Lore) and the playlist runs off the bottom of the screen like in the picture.  
![screenshot_20170104-211149](https://cloud.githubusercontent.com/assets/3997333/21669761/423cad64-d2c3-11e6-88b1-d0f08d7c2a6f.png)

**Comment by bottiger** [comment]
@ImDevinC Right. I'll make sure to get that fixed very soon. Thanks for reporting it.

**Comment by bottiger** [comment]
@ImDevinC I located and fixed the issue. It should be out shortly. If you subscribe to the beta version I will make it available in a few hours
