### ISSUE TITLE
Add refresh all podcasts option

### ISSUE THREAD

**Issue by smarquespt** [bottiger/SoundWaves#14]
Right now we can only refresh one subscription at a time.

Would you find to have an option to refresh all subscriptions at once?

It could be placed at the 3 dots icon from action bar.

What do you think?

**Comment by bottiger** [comment]
My personal vision is that you would never need it. I just wrote this in an e-mail to someone else

> ..... However the feeds to refresh automatically in the background (I don't remember if it's every 15 min or every hour[1]) so as soon as you have used it for a short time it's not really a problem any more. The only time I actually use the "refresh" option is when I know my favorite podcasts are about to be published and then I really only need to refresh that specific feed.

> Why do you want that feature?

> Vision: As soon as the app is out of beta I will start working on a server side component which will send push notifications whenever new episodes arrive. This should make your feeds be 100% up to date all the time.

That said, I have no problem implementing the feature in the short and medium term. In the long term I would like to hide since I do not feel one should need it. But maybe I'm wrong?

Why do you want it? I do understand we all have different needs but I would really like to understand why the current implementation doesn't work for you

**Comment by smarquespt** [comment]
> Why do you want it?

My device doesn´t have mobile data enabled so I only download episodes on Wi-fi. But I don´t have Wi-fi always enabled. Usually I only have it enabled as needed. Usually to download podcasts, search on f-droid or play store. When I done all of these, I turn it of. So the time span of 15 min or 1hour, could (sometimes) not fit my need.

Imagine that I turn on wifi only for 10 min. Then podcasts wil not be refreshed. With this option, I could turn on Wi-fi, refresh all feeds and download all episodes I want without having to open each subscription to do that. If that´s ok for  <5 podcasts, for 100 not so cool.

But this is only an idea. If you don´t think it´s worth, that´s fine by me. After all, this is your code, your choice.

**Comment by bottiger** [comment]
Again, I have no problem implementing it - people have all kinds of strange use cases :)

However, it sounds like your case could be mostly solved simply by forcing a refresh immediately when the device is connects to a wifi (and have not refreshed very recently).

**Comment by smarquespt** [comment]
> by forcing a refresh immediately when the device is connects to a wifi

Yes, that will solve the issue.

**Comment by bottiger** [comment]
It's implemented in the master branch and will be included in 0.84
