### ISSUE TITLE
Importing OPML file fails.

### ISSUE THREAD

**Issue by NitroNils** [bottiger/SoundWaves#140]
Trying to migrate from AntennaPod and exported OPML, but importing it from SoundWaves fail.
Using 0.158.358-free-release.
Tried several file managers: Huawei's EMUI one, stock, Ghost Commander.

PHONE_MODEL=ALE-L21_
BRAND=Huawei
ANDROID_VERSION=6.0
APP_VERSION_NAME=0.103
EMUI_VERSION=4.03

**Comment by bottiger** [comment]
@NitroNils How does it fail. Are you not allowed to pick the OPML file, or does it not import when you select it? Can you send me a copy of the file?

**Comment by NitroNils** [comment]
Attachment sent by mail to soundwavebugs.

**Comment by NitroNils** [comment]
It fails to open - selecting the file just sends me back to SoundWaves.

**Comment by bottiger** [comment]
@NitroNils Hi again. 

Could you please send me a debug log (settings -> advanced -> submit debug log) when the new version 0.158.8 hits F-droid tomorrow.

**Comment by NitroNils** [comment]
Yeah, you never received the previous one, did you? I'll be happy to! Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [bottiger/SoundWaves] Importing OPML file fails. (#140)From: Arvid Böttiger To: bottiger/SoundWaves CC: NitroNils ,Mention @NitroNils Hi again.
Could you please send me a debug log (settings -> advanced -> submit debug log) when the new version 0.158.8 hits F-droid tomorrow.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bottiger/SoundWaves","title":"bottiger/SoundWaves","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/bottiger/SoundWaves"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bottiger in #140: @NitroNils Hi again. \r\n\r\nCould you please send me a debug log (settings -\u003e advanced -\u003e submit debug log) when the new version 0.158.8 hits F-droid tomorrow."}],"action":{"name":"View Issue","url":"https://github.com/bottiger/SoundWaves/issues/140#issuecomment-309016275"}}}

**Comment by NitroNils** [comment]
Latest version here is 158.2!Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [bottiger/SoundWaves] Importing OPML file fails. (#140)From: Arvid Böttiger To: bottiger/SoundWaves CC: NitroNils ,Mention @NitroNils Hi again.
Could you please send me a debug log (settings -> advanced -> submit debug log) when the new version 0.158.8 hits F-droid tomorrow.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bottiger/SoundWaves","title":"bottiger/SoundWaves","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/bottiger/SoundWaves"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bottiger in #140: @NitroNils Hi again. \r\n\r\nCould you please send me a debug log (settings -\u003e advanced -\u003e submit debug log) when the new version 0.158.8 hits F-droid tomorrow."}],"action":{"name":"View Issue","url":"https://github.com/bottiger/SoundWaves/issues/140#issuecomment-309016275"}}}

**Comment by bottiger** [comment]
@NitroNils I'm sorry. But F-droid is having some build problems at the moment. Please wait until they have 0.158.8 ready

**Comment by NitroNils** [comment]
Will do! Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [bottiger/SoundWaves] Importing OPML file fails. (#140)From: Arvid Böttiger To: bottiger/SoundWaves CC: NitroNils ,Mention @NitroNils I'm sorry. But F-droid is having some build problems at the moment. Please wait until they have 0.158.8 ready

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bottiger/SoundWaves","title":"bottiger/SoundWaves","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/bottiger/SoundWaves"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bottiger in #140: @NitroNils I'm sorry. But F-droid is having some build problems at the moment. Please wait until they have 0.158.8 ready"}],"action":{"name":"View Issue","url":"https://github.com/bottiger/SoundWaves/issues/140#issuecomment-309424640"}}}

**Comment by NitroNils** [comment]
Guten Tag, Arvid!The bug is now gone. Importing the file works normally.Thank you for awesome responses and development!No need for the log now, aber?Best wishes!Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [bottiger/SoundWaves] Importing OPML file fails. (#140)From: anti.moral@gmail.comTo: bottiger/SoundWaves CC: Will do! Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [bottiger/SoundWaves] Importing OPML file fails. (#140)From: Arvid Böttiger To: bottiger/SoundWaves CC: NitroNils ,Mention @NitroNils I'm sorry. But F-droid is having some build problems at the moment. Please wait until they have 0.158.8 ready

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bottiger/SoundWaves","title":"bottiger/SoundWaves","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/bottiger/SoundWaves"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bottiger in #140: @NitroNils I'm sorry. But F-droid is having some build problems at the moment. Please wait until they have 0.158.8 ready"}],"action":{"name":"View Issue","url":"https://github.com/bottiger/SoundWaves/issues/140#issuecomment-309424640"}}}
