### ISSUE TITLE
Sound Engine Settings not persistent

### ISSUE THREAD

**Issue by anoadragon453** [bottiger/SoundWaves#142]
Hello there!

Currently using v0.158.2 from F-droid. It seems that changing any of the Sound Engine Settings (Playback speed, skip silence) do not have any effect and immediately reset to their default values after hitting the 'OK' button.

Android 7.1.2 - let me know if you need a logcat.

**Comment by bottiger** [comment]
@anoadragon453 Thank you for reporting this! I will push the fix today (might take a day to roll out)

**Comment by anoadragon453** [comment]
Will test when it hits F-droid. Thanks!
