### ISSUE TITLE
Can't tap last button at the bottom

### ISSUE THREAD

**Issue by aharris88** [bottiger/SoundWaves#144]
When I scroll all the way to the bottom, the Android controls cover up the plus button on the last item. In this case, I can barely tap on the description, which will expand the description, which will allow me to tap the plus icon, but this might not always work if the description was short. Either way, it's not a great user experience.

So, it should probably just have some extra padding at the bottom.

![screenshot_20170616-133957](https://user-images.githubusercontent.com/3266363/27242302-d19ce054-5299-11e7-9e0b-97d44c69dd28.png)

**Comment by bottiger** [comment]
@aharris88 I'll make sure to get it fixed asap

**Comment by bottiger** [comment]
@aharris88 It's fixed fixed in the master branch.
