### ISSUE TITLE
A little more space for sliding menu texts

### ISSUE THREAD

**Issue by smarquespt** [bottiger/SoundWaves#15]
Can you try use Portuguese version and see that sliding menu has some strings cut off?

1. Playlist filters -> Filtros da lista de reprodução - I guess 1/2 mm should be enough.

2. Show listened -> Mostrar reproduzidos (2 words, reproduzidos is in 2 lines)

3. Auto start next -> Iniciar seguinte automaticamente (3 words, automaticamente is in 2 lines)

Is it possible to make some changes in these? None of cutted strings have an feasible alternative.

**Comment by bottiger** [comment]
I will look into this. But it's a notorious difficult problem to get it right for all languages, screen sizes etc.

**Comment by smarquespt** [comment]
> get it right for all languages, screen sizes etc.

I understand the difficulties. Different screen size, languages... Maybe I´ll have to live with it.

**Comment by smarquespt** [comment]
@bottiger 

I´ve changed PT translation for 3.

I´ve made it like "Continuosly playing", as there is in Settings. It does same thing right?

**Comment by bottiger** [comment]
Yes, it does the same thing. The Navigation drawer is just a quick setting. However, 0.84 does include a lot of fixes regarding turning it on/off

**Comment by smarquespt** [comment]
> However, 0.84 does include a lot of fixes regarding turning it on/off

I will try it. But tell me, is it ok to add a newline in my translation if your fixes doesn´t work?

**Comment by bottiger** [comment]
Sure.

**Comment by bottiger** [comment]
@smarquespt I'm thinking of how to solve this issue. Can you please help me with a screenshot or two of the problem?

**Comment by smarquespt** [comment]
@bottiger 

If I only knew hot to get one...

But I´ll try to explain:

"Show listened" is " Mostrar reproduzidos. This should be:

1. As is -> but text is too long
2. Mostrar
    reproduzidos

But at the moment, in my device is
 
Mostrar
reproduzi
dos

"Auto start next" is "Reprodução contínua". This should be~

1. Same as 1. above
2. Reprodução
    contínua

But it is:

Reproduç
ão
contínua

**Comment by bottiger** [comment]
Can't you just press "volume down + power button" for 2 seconds on your phone? That will take a screenshot on most/all Android phones. 

In any case, it currently playing with adding a little more space, but I don't know if it will make it for 0.90

**Comment by smarquespt** [comment]
I´ve alredy attempted that. But it didn´t worked. About not making to 0.9 I have no problem with that. I´m still trying to know how the app works. Right now I have it on y device but it´s not my primary app. Sorry.

**Comment by bottiger** [comment]
No need to be sorry. I know it's rocky and I also fall back to other apps whenever I'm on the road and having problems for one reason or another.

**Comment by bottiger** [comment]
I finally took the time to look at this. The navigation drawer is now a little bit larger, the margins are a little bit smaller and I think everything fits. It will be there in the next release

Please reopen this issue if (when) you find other issues

**Comment by smarquespt** [comment]
@bottiger 

Indeed it´s fixed in 0.92
