### ISSUE TITLE
App constantly crashing

### ISSUE THREAD

**Issue by 464247853** [bottiger/SoundWaves#152]
Hey,
i want to try your app (downloaded it from fdroid) but it's crashing every minute so I can't use it at all :( I'm using a Samsung Galaxy S7 on the latest stock firmware without root/... 
I attached a bug report 
https://gist.github.com/b1024ee248fc713d5f995827136480f0
and enabled the option to automatically send crash reports.
Is there anything else I can do to help fix the problem?

**Comment by bottiger** [comment]
@464247853 Thank you for the report. I should be fixed in the master branch, which will be released soon. However, there might be other bugs like this, so please get back to me if you find another one.
