### ISSUE TITLE
Next episode starts playing from time previous podcast was paused

### ISSUE THREAD

**Issue by mike-cr** [bottiger/SoundWaves#157]
As title. If I listen to a particular episode up until, say, 23:42, the next episode I play will begin from that time.

Correct behaviour should start a new episode from the beginning.

**Comment by mike-cr** [comment]
Forgot to say: this is version 0.158.10 from F-Droid running on a Meizu m2 note running Flyme 6.1.0.0G (android version 5.1)

**Comment by bottiger** [comment]
@mike-cr This has been in the app previously. I have now found the reason it was disabled and fixed the issue - reenabling the feature. It will be in the next release.
