### ISSUE TITLE
Behaviour change of AlarmManager.set()

### ISSUE THREAD

**Issue by frankFic** [bottiger/SoundWaves#158]
For your information, the behaviour of `AlarmManager.set()` has changed since API 19. ([Doc](https://developer.android.com/reference/android/app/AlarmManager.html#set(int,%20long,%20android.app.PendingIntent))) After API 19, the time will be treated as inexact and the alarm will not be delivered before this time, but may be deferred and delivered some time later. This API is used in [PodcastUpdateReceiver](https://github.com/bottiger/SoundWaves/blob/603dfc2432de35b3b4bf6066e219b56fde079763/app/src/main/java/org/bottiger/podcast/receiver/PodcastUpdateReceiver.java#L65). I am not sure whether an exact time is needed here and only leave this information for your reference.

**Comment by bottiger** [comment]
@frankFic Thanks for taking the time to post this. I am aware of this, but fortunately and exact timer isn't needed. Also, for API level 21 and above the alarmmanager isn't used.
