### ISSUE TITLE
Crash on reverse sort

### ISSUE THREAD

**Issue by RigacciOrg** [bottiger/SoundWaves#165]
How to reproduce the crash:
Discover tab, enter one podcast URL, turn the switch "ON" to subscribe.
Subscription tab, tap on the subscribed podcast, dots menu, reverse order.

You can recover from this crash by clearing app data.

SoundWave 0.158.10 from F-Droid
Android 5.1.1 (CyanogenMod 12.1 Unofficial) on Samsung Galaxy S4 GT-I9515

**Comment by bottiger** [comment]
@RigacciOrg Thanks you for reporting this. However, I can not reproduce it in the most recent build. I will try to push it to F-Droid ASAP.

Please reopen this issue if the problem persist after the app is updated. It might take a few days for the update to be available on F-droid.
