### ISSUE TITLE
f-droid build for VC 409

### ISSUE THREAD

**Issue by Bubu** [bottiger/SoundWaves#166]
Fdroid tonight automaticlaly detected a new version `409` but I guess something went wrong as there is no `409` tag.

There is a 412 tag that contians the 409 version though.

Also there is a note that odd versions are dev versions? So should 412 which is 409 be added now?

**Comment by bottiger** [comment]
Hi. I don't know what was going on with F-droid.

However, it should be updated to the most recent version now.
