### ISSUE TITLE
SGU podcast crashes soundwaves 

### ISSUE THREAD

**Issue by AeliusSaionji** [bottiger/SoundWaves#168]
0.160.416 google release (hoping to switch to f-droid soon :)
Android 8.1
When I open the episode list, soundwaves just crashes. Here's the feed. I may have already sent a bug report through android feedback. https://feed.theskepticsguide.org/feed/sgu

**Comment by bottiger** [comment]
Thank for you finding this issue. I have fixed it in the master branch
