### ISSUE TITLE
Dark theme player tab unreadable

### ISSUE THREAD

**Issue by AeliusSaionji** [bottiger/SoundWaves#169]
Playlist filters menu: several items have black text on black background

the main player tab itself has a number of UI elements not visible in dark mode. The two I can tell are missing: the text "1.0x", the trashcan delete icon, and the ... icon to expand that menu

Android 8.1
0.160.416 google release

**Comment by bottiger** [comment]
Thanks for the notice. I see your point and will get it fixed in the next release. Which should be out in a day or two.

**Comment by bottiger** [comment]
I have fixed the issues, and a few more, in the master branch. Please let me know if you find more problems.
