### ISSUE TITLE
Import opml from settings

### ISSUE THREAD

**Issue by AeliusSaionji** [bottiger/SoundWaves#170]
I can import an opml from the main interface, both where subscriptions are empty, and from the ... menu.

The import option within the settings page gives me a file picker, but silently does nothing with it. Seems like this one isn't properly hooked up in the code.

**Comment by AeliusSaionji** [comment]
I'm on Oreo 8.1 if that matters, 160.2.422-google-release

**Comment by bottiger** [comment]
I am actually aware of this. Think you for reminding me.
