### ISSUE TITLE
Fast forward skips the same time as Rewind

### ISSUE THREAD

**Issue by icubyx** [bottiger/SoundWaves#172]
Suppose I set FF to 1 min and Rewind to 30 sec. On clicking FF and Rewind, both skip by 30 sec and not 1 minute and 30 sec each. If I set Rewind to 10 sec, it skips by 10 sec and so on. 
Hardware: Lenovo Z2 Plus, 
OS: Custom Android Oreo 8.1
App version: 0.160.2.422-google-release

**Comment by bottiger** [comment]
Thank you for reporting this.

I has been fixed in the master branch
