### ISSUE TITLE
Tag "104" is at versioncode 103

### ISSUE THREAD

**Issue by krt16s** [bottiger/SoundWaves#22]
Is tag "104" meant to be a release? Because the tag does not have a matching vercode. If it was a real release, i can force the vercode to 104 for fdroid builds.

**Comment by bottiger** [comment]
Thank you for this. 

Yes, I mess up with 104. I would be very nice if you could force f-droid to build tag 104. I will try to automate releases in the future since I tend to forget something - one way or the other.

**Comment by krt16s** [comment]
I am too late for forcing 104 VC, but it will build tag 104 as it is (with vc103).  The next version should fix this anyway.
