### ISSUE TITLE
Import not working

### ISSUE THREAD

**Issue by smarquespt** [bottiger/SoundWaves#23]
Import/export option isn´t working on 0.86 release.

**Comment by bottiger** [comment]
Which version of android are you running? And does your device have an SD card or not?

(On an unrelated note, I won't be able to do any programming this week)

**Comment by smarquespt** [comment]
> Which version of android are you running

I´m on 4.3

> And does your device have an SD card or not?

Yes

> (On an unrelated note, I won't be able to do any programming this week)

No problem. Take your time.

**Comment by bottiger** [comment]
I'm reopening this issue. I think there are some issues I need to investigate. I'm not sure if android can write to external storage while connected to a computer.

**Comment by bottiger** [comment]
I hope the problem is fixed now, but I am not completely sure
