### ISSUE TITLE
FC when subcribing from gPodder

### ISSUE THREAD

**Issue by smarquespt** [bottiger/SoundWaves#24]
1. Search "Outra coisa" on gPodder.
2. Subscribe

~~Result -> Crash~~

It doesn´t crash but since there is more than 1 similar podcast, even tough it says it´s subscribed it is not

**Comment by bottiger** [comment]
I didn't quite understand the problem. I know that the app crashes sometimes - I intend to fix this.

However, what is the other issue you are talking about?

**Comment by smarquespt** [comment]
I´ve tested again and I have no such issue. Sorry.
