### ISSUE TITLE
Support for landscape mode

### ISSUE THREAD

**Issue by willemw12** [bottiger/SoundWaves#31]
Please add support for landscape mode. All the activity screens are now always in portrait mode, except for the Settings screen.

**Comment by bottiger** [comment]
I plan to support landscape mode at some point, the big question is how to prioritize it compared to all my other bugs and missing features.

Could you please elaborate on why you want it? I personally never really needed it on my phone. Are you using a tablet?

**Comment by willemw12** [comment]
Yes, I am using a 7" tablet (Nexus 7). The orientation of a tablet is usually in landscape. When I put the tablet on a stand, for example to listen to a podcast, it is in landscape mode. It is not practical to use the app, unless you don't mind picking the tablet up every time you use the app.

Simply allowing the screens to rotate is what would solve the issue. No special tablet/landscape layouts are necessary, I would think.

**Comment by bottiger** [comment]
I'm glad you would be satisfied with simply rotating the current layout.

I have a nexus 7 myself and honestly I think the current user experience is pretty poor. However, phones are currently the primary focus so I do think the big tablet layout is at least a few months away.

Just rotating the layout is also not as easy as it sounds. It could actually cause some new unintended bugs.

My suggestion is. How about an experimental option in the advanced settings category where you can turn on rotation?

**Comment by willemw12** [comment]
Good suggestion.

**Comment by bottiger** [comment]
Pushed to master. Will be in 0.86

**Comment by willemw12** [comment]
Works well. No problems.

**Comment by bottiger** [comment]
Good to hear :) This is valuable feedback. However, I still have some unsafe code which will need to be cleaned up before I make it more accessible
