### ISSUE TITLE
Cannot close the app

### ISSUE THREAD

**Issue by willemw12** [bottiger/SoundWaves#35]
There is no way to exit the app. Expected to be able to close the app according to the latest UI guidelines.

Actually, it is related to the app's notification:
There is no way to close the app's notification, either by a "close" button on the notification area or by exiting the app.

**Comment by bottiger** [comment]
I am not able to look into the guidelines right now. Could you please elaborate on how you expected to be able to close the app?

**Comment by willemw12** [comment]
There are general UI guidelines. However, I am not sure there are specific guidelines on exiting an app.

Have seen several ways of exiting an app: single tap on the backward button, double tap on the backward button, exit option in the main menu on the left-hand side of the screen.

Without knowing more, at the moment, I would choose for: single tap on the backward button.

**Comment by bottiger** [comment]
@willemw12

I am confused by this. I have no problems closing the application by any of these methods, maybe I misunderstand something.

Can you please tell me which device you use and which steps I need to do to reproduce the problem.

**Comment by willemw12** [comment]
I cannot reproduce the issue or I was mistaken. Please close the issue.

Tapping the backward button closes the app. Swiping the notification closes the notification.

**Comment by bottiger** [comment]
Then it sounds like a case of the application not responding for one reason or another.

**Comment by willemw12** [comment]
This may have been the issue I was experiencing:

Issue: the player continues playing even when exiting the app (through the Backward button from the main screen). Only after swiping the app from the app history list, does the player stop.

Expected: when exiting the app from either 1) the app itself or 2) from the notification (that would a new feature), the player should stop playing.
