### ISSUE TITLE
Sliding menu option "Show" retains cancelled subscription

### ISSUE THREAD

**Issue by smarquespt** [bottiger/SoundWaves#39]
How to reproduce:

Search on gpodder and add pod1, pod2, pod3

Open sliding menu and option "Show:" shows all episodes, pod1, pod2, pod3

Cancel subscription pod1, pod2

Observed behaviour:

Option "Show" shows shows all episodes, pod1, pod2, pod3

Expected:

"Show:" only should show podcasts subscribed.

**Comment by bottiger** [comment]
True. That filter needs some work. As far as I remember it also doesn't persist your selection.
I will make sure this is fixed for 0.90

**Comment by smarquespt** [comment]
Milestone 1.0?

**Comment by bottiger** [comment]
@smarquespt No, it's more or less now :) I've been pushing everything playlist related in front of me for a while now. But I've finally started working on it. It will be in 0.94 or 0.96 - depending on where I start

**Comment by bottiger** [comment]
Fixed in the master branch
