### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by a1291762** [bottiger/SoundWaves#4]
RAZR i running 4.1.2. SoundWaved 0.7 from f-droid.

03-10 21:41:43.413 E/AndroidRuntime(21001): FATAL EXCEPTION: main
03-10 21:41:43.413 E/AndroidRuntime(21001): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.bottiger.podcast/org.bottiger.podcast.MainActivity}: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x12
03-10 21:41:43.413 E/AndroidRuntime(21001): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2115)
03-10 21:41:43.413 E/AndroidRuntime(21001): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2153)
03-10 21:41:43.413 E/AndroidRuntime(21001): 	at android.app.ActivityThread.access$700(ActivityThread.java:137)
03-10 21:41:43.413 E/AndroidRuntime(21001): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1246)
03-10 21:41:43.413 E/AndroidRuntime(21001): 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-10 21:41:43.413 E/AndroidRuntime(21001): 	at android.os.Looper.loop(Looper.java:137)
03-10 21:41:43.413 E/AndroidRuntime(21001): 	at android.app.ActivityThread.main(ActivityThread.java:5031)
03-10 21:41:43.413 E/AndroidRuntime(21001): 	at java.lang.reflect.Method.invokeNative(Native Method)
03-10 21:41:43.413 E/AndroidRuntime(21001): 	at java.lang.reflect.Method.invoke(Method.java:511)
03-10 21:41:43.413 E/AndroidRuntime(21001): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
03-10 21:41:43.413 E/AndroidRuntime(21001): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
03-10 21:41:43.413 E/AndroidRuntime(21001): 	at dalvik.system.NativeStart.main(Native Method)
03-10 21:41:43.413 E/AndroidRuntime(21001): Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x12
03-10 21:41:43.413 E/AndroidRuntime(21001): 	at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:463)
03-10 21:41:43.413 E/AndroidRuntime(21001): 	at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:5622)
03-10 21:41:43.413 E/AndroidRuntime(21001): 	at android.widget.LinearLayout$LayoutParams.<init>(LinearLayout.java:1809)
03-10 21:41:43.413 E/AndroidRuntime(21001): 	at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:1721)
03-10 21:41:43.413 E/AndroidRuntime(21001): 	at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:58)
03-10 21:41:43.413 E/AndroidRuntime(21001): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:748)
03-10 21:41:43.413 E/AndroidRuntime(21001): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
03-10 21:41:43.413 E/AndroidRuntime(21001): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
03-10 21:41:43.413 E/AndroidRuntime(21001): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
03-10 21:41:43.413 E/AndroidRuntime(21001): 	at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:2806)
03-10 21:41:43.413 E/AndroidRuntime(21001): 	at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:2866)
03-10 21:41:43.413 E/AndroidRuntime(21001): 	at com.android.internal.policy.impl.PhoneWindow.getDecorView(PhoneWindow.java:1560)
03-10 21:41:43.413 E/AndroidRuntime(21001): 	at android.support.v7.app.ActionBarActivityDelegateBase.onCreate(ActionBarActivityDelegateBase.java:140)
03-10 21:41:43.413 E/AndroidRuntime(21001): 	at android.support.v7.app.ActionBarActivity.onCreate(ActionBarActivity.java:123)
03-10 21:41:43.413 E/AndroidRuntime(21001): 	at org.bottiger.podcast.TopActivity.onCreate(TopActivity.java:23)
03-10 21:41:43.413 E/AndroidRuntime(21001): 	at org.bottiger.podcast.ToolbarActivity.onCreate(ToolbarActivity.java:46)
03-10 21:41:43.413 E/AndroidRuntime(21001): 	at org.bottiger.podcast.DrawerActivity.onCreate(DrawerActivity.java:133)
03-10 21:41:43.413 E/AndroidRuntime(21001): 	at org.bottiger.podcast.FragmentContainerActivity.onCreate(FragmentContainerActivity.java:64)
03-10 21:41:43.413 E/AndroidRuntime(21001): 	at org.bottiger.podcast.MainActivity.onCreate(MainActivity.java:127)
03-10 21:41:43.413 E/AndroidRuntime(21001): 	at android.app.Activity.performCreate(Activity.java:5058)
03-10 21:41:43.413 E/AndroidRuntime(21001): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
03-10 21:41:43.413 E/AndroidRuntime(21001): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2079)
03-10 21:41:43.413 E/AndroidRuntime(21001): 	... 11 more

**Comment by bottiger** [comment]
Thank you for taking the time to report this. I believe I have found and fixed the problem. The fix will be included in 0.74
