### ISSUE TITLE
Black text in black/dark background

### ISSUE THREAD

**Issue by frazzmark** [bottiger/SoundWaves#43]
Right after i installed it and started playing something I noticed this issue: I can't read a thing in the notification! The text is black, my background black too.

**Comment by bottiger** [comment]
@frazzmark  Really, I had no idea that was possible. Can you please attach a screenshot?

**Comment by frazzmark** [comment]
![screenshot_2015-04-18-12-00-14](https://cloud.githubusercontent.com/assets/7524830/7214972/d1fd7b3a-e5c2-11e4-9de0-0e5808f0ded1.png)
here, i reinstalled everything and it's happening again. using galaxy s3 i9300, kitkat 4.4 and ART

**Comment by bottiger** [comment]
Yeah, that's really bad :) I am just about to release a new version. If it's a quickfix I'll put it in, otherwise it will be another week or two.

Thanks

**Comment by bottiger** [comment]
@frazzmark  I'm sorry, but it didn't make the cut for 0.90, but it will definitively be in 0.92

**Comment by bottiger** [comment]
I have fixed it in the current master. Will in included in the next release
