### ISSUE TITLE
There are two Settings menus

### ISSUE THREAD

**Issue by willemw12** [bottiger/SoundWaves#44]
There are two Settings menus: one in the left-hand side menu, one in the right-hand side overflow menu. There should only be one menu.

**Comment by bottiger** [comment]
The one in the navigation drawer (swipe in from the left) was initially added just to test the look and feel of having a few menu items there. However, it is also quite common for apps to place the setting menu there.
        
The one in the right side (the ... button)  was there before I had the navigation drawer and have not been removed.
        
The reson I still have two is that I have not made up my mind yet. I am leaning towards just keeping it in the (...)-menu but I'm not sure, and I can't find any official guidelines on the matter.
        
I believe it looks nicer in the navigation drawer but I also feel a lot of users are not confirtable enough with swiping in from the left (or pressing the burger) that you can expect them to look there. 
        
What do you think?

**Comment by willemw12** [comment]
I am all for following the latest guidelines and, in most cases, not mix older with newer guidelines.

If the app layout includes a hamburger menu (navigation drawer on the left), then the action bar's overflow menu on the right should only contain immediate/frequent actions, not infrequent actions such as Settings.
If there is no hamburger menu, then Settings goes in the overflow menu.

http://developer.android.com/design/patterns/settings.html
(http://developer.android.com/guide/topics/ui/settings.html)

**Comment by bottiger** [comment]
Fixed in the master branch
