### ISSUE TITLE
Playlist mode not persistent

### ISSUE THREAD

**Issue by smarquespt** [bottiger/SoundWaves#53]
The playlist mode introduced in 0.94 is not persistent. Always falback to Place episodes manually

**Comment by bottiger** [comment]
Yeah, it's still buggy. Better in 0.94.2, but still buggy

**Comment by bottiger** [comment]
Fixed in master branch - i hope. There could be more edge cases

**Comment by smarquespt** [comment]
Do you think we need a tab for this one? Why mot put it in settings? It could be shown on first run as a dialog and after in settings.

**Comment by bottiger** [comment]
I agree it should be in the settings as well. Basically everything in the navigation drawer should also be accessible elsewhere. 

However, the "playlist mode" (which needs a better name) should already be shown in the playlist tab until the playlist has been populated the first time.

**Comment by smarquespt** [comment]
2015-05-14 10:50 GMT+01:00 Arvid Böttiger <notifications@github.com>:

> I agree it should be in the settings as well. Basically everything in the
> navigation drawer should also be accessible elsewhere.
>
> However, the "playlist mode" (which needs a better name)
>

Maybe "Playlist Filling"

>


-- 
Sérgio Marques
