### ISSUE TITLE
Reduce font size in Subscription tab

### ISSUE THREAD

**Issue by smarquespt** [bottiger/SoundWaves#54]
Due to different languages, Portuguese text is cutted in Subscription tab. And arrows are also very big.

The cutted text is "Playlist" and "Discover". All remaining texts are fine.

Is it possible to reduce font size in it?

**Comment by bottiger** [comment]
Sure - I try to put it in a quick 94.4 service release.

**Comment by bottiger** [comment]
Fixed in master branch. Please re-open if you find other problems :)
