### ISSUE TITLE
iTunes integration not working

### ISSUE THREAD

**Issue by smarquespt** [bottiger/SoundWaves#55]
For me, Discover in iTunes is not working. Anyone can confirm it?

**Comment by bottiger** [comment]
It may (or may not) be the same issue as with gpodder. Are you trying with 94.2 ?

**Comment by smarquespt** [comment]
No. I´m on 0.94. Later I will try with 0.94.2 if available in fdroid.

2015-05-13 15:24 GMT+01:00 Arvid Böttiger <notifications@github.com>:

> It may (or may not) be the same issue as with gpodder. Are you trying with
> 94.2 ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bottiger/SoundWaves/issues/55#issuecomment-101684836>.
>



-- 
Sérgio Marques

**Comment by bottiger** [comment]
@smarquespt Cool, thank you very much. 94.2 should be available now

**Comment by smarquespt** [comment]
Working in 0.94.2
