### ISSUE TITLE
it does not show up in the share app list

### ISSUE THREAD

**Issue by irregularisnotrandom** [bottiger/SoundWaves#56]
Hi
This app does not show up in the list for url sharing from browser, so one has to put urls manually.

Thanks

**Comment by bottiger** [comment]
I'll try to get this fixed for the next release.

**Comment by irregularisnotrandom** [comment]
Thanks

**Comment by bottiger** [comment]
@irregularisnotrandom You closed it fast :) I'm about to push 0.96 so please let me know if it does what you want. If it doesn't please let me know where it fails.
