### ISSUE TITLE
Support External Players for Video Playback

### ISSUE THREAD

**Issue by Cadair** [bottiger/SoundWaves#57]
I really like the look of soundwaves but I watch a lot of video podcasts, it would be great if you could configure an external player for video files.

**Comment by bottiger** [comment]
I was thinking a lot about video podcasts when I started the project. I do watch them, but I know other people do. I think SoundWaves should continue to focus on the audio podcasts until that part is nailed, done and bug free.

However, just opening a video on an external player seems like a reasonable compromise for now. I will try to implement it in the near fututre.

**Comment by Cadair** [comment]
@bottiger I agree that focus is always good. I would prefer opening in an external player anyway, as video gets quite complex and you might as well just give it to someone else who has put a lot of work into it, like VLC.

Thanks for a cool app.

**Comment by bottiger** [comment]
@cadair this was surprisingly tricky to get right, but I finally have a first implementation in the upcoming 0.106 version, which should be out later today

Cheers
