### ISSUE TITLE
Cannot read or select podcast - obscured by system buttons

### ISSUE THREAD

**Issue by snelltheta** [bottiger/SoundWaves#58]
Scroll to the bottom of the list, and what do I get? I cannot scroll further. See podcast obscured by the buttons at the bottom?

![tmp_5339-screenshot_2015-09-14-19-19-401232023010](https://cloud.githubusercontent.com/assets/12014328/9866352/4bccf8aa-5b16-11e5-8d42-7d20a2eb3b17.png)

**Comment by bottiger** [comment]
I'll try to get it fixed. As far as I remember there was something tricky about it, but it was a long time ago since I looked at it and everything has matured *a lot* since then.

**Comment by bottiger** [comment]
Fixed in upcoming version 0.106

**Comment by snelltheta** [comment]
This problem is happening again with version 0.128.2
