### ISSUE TITLE
Dark theme enabled; doesn't work

### ISSUE THREAD

**Issue by snelltheta** [bottiger/SoundWaves#59]
Pic says it all: white text and no dark background. Generally unreadable.

![tmp_5339-screenshot_2015-09-14-19-28-47-1553387998](https://cloud.githubusercontent.com/assets/12014328/9866422/fddcb102-5b16-11e5-80f0-2759b5b861d6.png)

**Comment by bottiger** [comment]
Thank you for this. I know it's broken but so far it has only been on my "medium term" todo list. Is it important to you?

**Comment by snelltheta** [comment]
Personally, I prefer a dark mode, but I wouldn't really regard this as critical.

**Comment by PanderMusubi** [comment]
Please fix this. When a user has all his or her apps in dark theme, this one sticks out by not supporting it. Please, use as much of the system's dark theme as possible.

**Comment by bottiger** [comment]
@PanderMusubi Sorry for being absent for such a long time. The dark theme should be working in the latest update (0.132)
