### ISSUE TITLE
The full screen button crahes app

### ISSUE THREAD

**Issue by snelltheta** [bottiger/SoundWaves#62]
It's the button to the right of the clock with z button. Instant crash.

![tmp_5339-screenshot_2015-09-14-19-40-44424168652](https://cloud.githubusercontent.com/assets/12014328/9866615/23c3ce58-5b19-11e5-913d-6787197e31b3.png)

**Comment by bottiger** [comment]
Thank you very much. This has been fixed and will be pushed out later today.
