### ISSUE TITLE
Import action not working

### ISSUE THREAD

**Issue by smarquespt** [bottiger/SoundWaves#63]
In release 0.106 import option is not working. When i try to import an .opml file nothing is done.

I´ve tried to put it in sd card and in internal storage but soundwaves always says that ther is no podcasts.opml file.

My android system is 4.3.

**Comment by smarquespt** [comment]
@bottiger 

no problem in f-droid build. only in play build.

**Comment by bottiger** [comment]
@smarquespt This should also be fixed in the upcoming 0.108, but it's a bit more phone specific, so please reopen this if the issue is not fixed.

**Comment by smarquespt** [comment]
Also fixed as stated in https://github.com/bottiger/SoundWaves/issues/64
