### ISSUE TITLE
FC whe accesing settings

### ISSUE THREAD

**Issue by smarquespt** [bottiger/SoundWaves#64]
Relase 0.106 on android 4.3

Overflow menu -> Settings gives immediate FC

**Comment by smarquespt** [comment]
@bottiger 

no problem in f-droid build. only in play build.

**Comment by bottiger** [comment]
@smarquespt I have fixed the issue and it will be released ASAP (0.108)

**Comment by smarquespt** [comment]
@bottiger 

indeed. fixex in latest release
