### ISSUE TITLE
Soundwaves crashes on incoming call during playback

### ISSUE THREAD

**Issue by snelltheta** [bottiger/SoundWaves#65]
Not sure if it will crash in any case similar.

**Comment by bottiger** [comment]
@snelltheta Are running android M ?

**Comment by snelltheta** [comment]
Lollipop

**Comment by bottiger** [comment]
@snelltheta  really? I'll have a look at it ASAP then

**Comment by bottiger** [comment]
Fixed it in the master branch. Will be in the next release
