### ISSUE TITLE
Version 0.128 crashes immediately upon launch

### ISSUE THREAD

**Issue by snelltheta** [bottiger/SoundWaves#71]
Tested on LG G3

**Comment by bottiger** [comment]
I am sorry. I cannot find your issues in the crash logs. Are you using the version from F-droid or Google play?

There is another issue regarding users who have connected the app to gPodder, have you done that?

**Comment by smarquespt** [comment]
@bottiger 

It also happens to me on the f-droid release. Play release is still on 0.126 (at least for me).

**Comment by bottiger** [comment]
I think I found and fixed the problem. I will push it later today and should be on f-droid tomorrow.

**Comment by snelltheta** [comment]
I can confirm a fix on my device! :)
