### ISSUE TITLE
Subscription columns: a list

### ISSUE THREAD

**Issue by Primokorn** [bottiger/SoundWaves#74]
Hi,
Select this option in the settings and go back to the Subscriptions tab.
You should see this bug: http://www.image-heberg.fr/files/14659245761716.png

Thank you.

**Comment by bottiger** [comment]
@Primokorn Thank you very much. I'll make sure to push a fix for this ASAP (1-3 days)

**Comment by bottiger** [comment]
Fixed in the upcoming 0.136.4
