### ISSUE TITLE
Text bug in the settings of a podcast

### ISSUE THREAD

**Issue by Primokorn** [bottiger/SoundWaves#75]
Hi,

From the Discover tab, choose a podcast (Security now here), then hit the Settings floating button.
You shoul have this: http://www.image-heberg.fr/files/14659245761926.png

Thank you.

**Comment by bottiger** [comment]
@Primokorn Thank you for reporting this. I will fix it in the near future, but I do not think it will make it into the next release.

**Comment by bottiger** [comment]
@Primokorn Fixed. Will be in the next release
