### ISSUE TITLE
[Bug] Unsubscribe does not work.

### ISSUE THREAD

**Issue by collectorgeneral** [bottiger/SoundWaves#78]
The unsubscribe button does nothing. 

(I usually write a bit more verbose comments, but I do not know what else to say.)

Phone info:
One Plus One aka Bacon aka A0001 running Android 6.0.1 (Cyanogen OS 13.1)

If you need additional info, let me know.

**Comment by bottiger** [comment]
@collectorgeneral I did fix an issue related to this in the most recent version. However, F-Droid hasn't updated the app yet. Please let me know if the problem is still there when you are updated to 0.136.10.

**Comment by collectorgeneral** [comment]
Alright, I will wait for F Droid to update its packages (hopefully soon) and I will let you know!

**Comment by bottiger** [comment]
@collectorgeneral  Yeah, there is definitly something wrong there. I'll get it fixed ASAP
