### ISSUE TITLE
Can't play files encoded Opus

### ISSUE THREAD

**Issue by Yxogenium** [bottiger/SoundWaves#79]
- Issue:
  RSS feeds providing files encoded in Opus cannot currently be used with SoundWaves : the podcast is added in the subscription list, and I can click on the play button, but no sound is actually played.
- Expected behavior:
  Ideally, SoundWaves should be able to play streams in opus. If this is not possible, it should at least show an error message.
- Reproducing:
  The CRE podcast provides both Opus and OggVorbis streams :
  - Ogg: http://cre.fm/feed/oga/
  - Opus: http://cre.fm/feed/opus/
    The first one works fine, the second doesn't.

(OS: CyanogenMod 13.0)

**Comment by bottiger** [comment]
@Yxogenium Thank you for reporting this. Fortunately this is actually already in the next release which will be released in a not too distant future. 

However, it still has some bugs I need to fix. 

If you want to test it out I will push it to the beta channel later today. You can opt in here
https://play.google.com/apps/testing/org.bottiger.podcast

**Comment by Yxogenium** [comment]
Wonderful!
Unfortunately I won't be able to  test it because I only have F-Droid on my device, but I'd be glad to report on it once it's released on F-Droid.
