### ISSUE TITLE
"Options" missing in left menu

### ISSUE THREAD

**Issue by github-user-1** [bottiger/SoundWaves#83]
I think the Options-dialog should be accessible via the left menu (the one selected via the three bars icon):
![screenshot_2016-12-05-15-17-51](https://cloud.githubusercontent.com/assets/6796538/20888345/64e2b050-baf6-11e6-88f6-c61acadd4587.png)

**Comment by bottiger** [comment]
@github-user-1 Thank you for taking the time to post here. Could you please elaborate?

**Comment by github-user-1** [comment]
What i meant is the following (not really important; rather a nice-to-have from my understanding/viewpoint): there are two menus accessible in this app on the top of the screen - on the left three bars, on the right three dots.

My general expectations is that the left menu (three bars) is the one where general settings, changes, version information etc. is accessible.
The right menu (three dots) is the one where I would expect very specific things to do with the item that is currently active or shown.

Maybe have a look at other apps how and where they put different actions items (like Options/Settings, etc.). But this is really only a comment (not a real issue)...

**Comment by bottiger** [comment]
I agree. I actually has settings there back in the days, but it was removed because the material guidelines said it didn't belong there.

However, I can see they have changed their minds, so I'm adding it back. It will be available in 0.148.12
