### ISSUE TITLE
Podcast Logo not shown

### ISSUE THREAD

**Issue by github-user-1** [bottiger/SoundWaves#84]
When adding a podcast (example "Zeitzeichen" from WDR1) the logo is not shown - it does show in other podcast apps though:

![screenshot_2016-12-05-15-16-16](https://cloud.githubusercontent.com/assets/6796538/20888435/e3434dec-baf6-11e6-8acb-58d619b1ca84.png)

**Comment by bottiger** [comment]
@github-user-1 I know there can be an issue here. I will start working on it at once. Which podcats did you subscribe to? and did the logo appear after restarting the app?

**Comment by github-user-1** [comment]
Restarting didn't help unfortunately - still showing the same generic logo.

I added the podcast via the gPodder search (included in the app, left-most tab) - searching for "zeitzeichen" and selecting the third one from the top. There (i.e. in this list), the podcast logo is shown correctly btw:

![screenshot_2016-12-05-15-38-41](https://cloud.githubusercontent.com/assets/6796538/20888967/0f605e2c-baf9-11e6-8cd3-65d0ac61277e.png)

**Comment by bottiger** [comment]
I'm closing this one since it must be related to #85
