### ISSUE TITLE
Dark Theme - Player icon black (instead of white)

### ISSUE THREAD

**Issue by github-user-1** [bottiger/SoundWaves#86]
In the dark theme the Player icon show in black (instead of white like the other icons, cf. screenshot below) which makes it hard to see and seems inconsistent:

![screenshot_2016-12-05-15-29-51](https://cloud.githubusercontent.com/assets/6796538/20888637/afb05b7c-baf7-11e6-8feb-480d8a4b0e3b.png)

**Comment by bottiger** [comment]
@github-user-1 Thanks. This is fixed in the upcoming version 0.148.12
