### ISSUE TITLE
Choose OPML location

### ISSUE THREAD

**Issue by AugerC** [bottiger/SoundWaves#87]
Right now, you need to have a file in a certain location, it would be easier for the users to select the file themselves.
This would need a FileSystem popup or ask Android for it.

**Comment by bottiger** [comment]
It's hard to disagree :) The reason it's done the way it is is because it didn't have time to do a better solution  at the time. However, I do now. I will look into if there is an easy way to create a file browser and locate the file manually.

**Comment by AugerC** [comment]
I'm on it, don't worry ^^

**Comment by bottiger** [comment]
@AugerC On what? it seems [like it's pretty easy to pick a file](http://stackoverflow.com/questions/22619325/android-directory-and-file-chooser-android-library). Are you going to create a pull request?

**Comment by AugerC** [comment]
Well, i was setting up the project to work on it this week. If you can do this faster, no problem (it will take some hours to know all folders and files you have here xD ) i will go for some other functionality.

**Comment by bottiger** [comment]
@AugerC No problem, I'll just let it sit and wait then. But there are also plenty of other things to work on :)
