### ISSUE TITLE
Dark-Theme: Text/Icon color should be white (instead of black)

### ISSUE THREAD

**Issue by github-user-1** [bottiger/SoundWaves#88]
I think a few items of the playlist should be in white (instead of black) in the Dark-Theme - the titel of the podcast, the heart symbol and the cancel icon (cross in circle). See screenshot below:

![screenshot_2016-12-07-14-24-42](https://cloud.githubusercontent.com/assets/6796538/20972094/b0b4c48c-bc8b-11e6-97fd-006308840770.png)

**Comment by bottiger** [comment]
Fixed in 0.148.16

**Comment by github-user-1** [comment]
I just came across two more places where I think the text color should be white (instead of black) for the Dark-Theme - in the Playlist-Filter-Menu and the left navigation (options, etc.) - see screenshots below:

![screenshot_2016-12-14-11-14-28](https://cloud.githubusercontent.com/assets/6796538/21178307/d0c62a3a-c1e6-11e6-9b29-75051c249349.png)

![screenshot_2016-12-14-11-14-10](https://cloud.githubusercontent.com/assets/6796538/21178312/d319253a-c1e6-11e6-9d57-c70e659325fc.png)

**Comment by github-user-1** [comment]
and one more I found - if one expands an episode in the Playlist - the heart (what does it mean/stand for btw?) and the cross - they should be white instead of black I assume:

![screenshot_2016-12-14-11-41-35](https://cloud.githubusercontent.com/assets/6796538/21181167/79173ae6-c1f4-11e6-8d9f-496541de99fd.png)
