### ISSUE TITLE
Tranlsation strings meta issue (errors or missing)

### ISSUE THREAD

**Issue by smarquespt** [bottiger/SoundWaves#9]
@bottiger 

I´m opening this issue to report missing strings from source code.

Issues I´ve found so far:

Release 0.78.1

1. Drawer - Playlist tab -> "Playlist is empty"
2. Drawer - Subscription tab -> "Add new podcasts by using.... manually"
3. Sliding menu -> "Show listened"
4. Sliding menu -> "Auto start next"
5. 3 dots menu top right - Add podcast -> "Add podcast", "Please enter a URL", "Cancel", "Ok"
6. Drawer - Playlist tab - show menu -> There are 2 strings with "Download all" text
7. Drawer - Playlist tab - Import Opml -> "x subscriptions was imported". 

For 7., there should be 2 strings, because opml file can have 1 subscription only. So this should be:

1 subscription was imported; n subscriptions were imported

**Comment by bottiger** [comment]
Thank you very much for this. I truly appreciate that you take the time to report these issues.

**Comment by bottiger** [comment]
I have [updated the master branch](https://github.com/bottiger/SoundWaves/commit/d8b8361d3ef641472ce592d79f5d78dae0d9125e) and moved all the strings above to the resource file.

I have also made sure that the resource files have been [updated on transifex](https://www.transifex.com/projects/p/soundwaves/).

I have also fixed a fair amount of bugs which I will push in a new release whenever you are ready :)

**Comment by smarquespt** [comment]
@bottiger 

Please wait a little for me to update strings.

**Comment by bottiger** [comment]
Sure - no problem. Take your time

**Comment by smarquespt** [comment]
@bottiger 

Release 0.80

1. sliding menu -> "Playlist filters"
2. sliding menu -> "Player settings"
3. Import OPML -> "OPML not found. Please name... (SD card)"
4. Search field for gppoder -> "Search using gpodder.net"
5. Search field for gppoder - Search podcast - Choose one -> "Subscribing to:"

**Comment by bottiger** [comment]
Thanks, they should be fixed as well now.

**Comment by smarquespt** [comment]
@bottiger 
How? no commit was made after 0.80 release.

**Comment by bottiger** [comment]
Don't worry. I have just not pushed yet. I'll do it now

**Comment by smarquespt** [comment]
@bottiger 

Sorry. https://github.com/bottiger/SoundWaves/pull/12
