### ISSUE TITLE
Mobile Data Traffic with Option to Download via WLAN only

### ISSUE THREAD

**Issue by github-user-1** [bottiger/SoundWaves#91]
I have a rather low limit on the mobile data traffic per month, so I want to have this app to use WLAN only - I selected the option to download via WLAN only (see below), however, the app still downloads a few MBs over mobile connections anyhow (probably not podcasts themselves, as then the data volume would be higher, but likely some podcast-lists or so):

![screenshot_2016-12-10-23-51-38](https://cloud.githubusercontent.com/assets/6796538/21078939/d2d395ac-bf79-11e6-8721-888cd11e8945.png)

![screenshot_2016-12-10-23-51-08](https://cloud.githubusercontent.com/assets/6796538/21078941/d67e4422-bf79-11e6-813c-40d81b6b88e2.png)

**Comment by bottiger** [comment]
@github-user-1 Thank you for reporting this. This has a very high priority for me!

I could be that the feed refreshes regardless of this setting, or it might be that the podcast images are refreshed. I will investigate and get back to you ASAP. But I cannot promise it will be today.

**Comment by bottiger** [comment]
@github-user-1 I have double checked all network activity in the most recent release (0.148.18). I did locate some potential issues which I think could cause the data usage you are seeing.

Please confirm that it has been fixed.

**Comment by github-user-1** [comment]
Hi - yes it seems to be fixed right now. The mobile data consumed by this app is not increasing anymore the last days.

**Comment by bottiger** [comment]
@github-user-1 Good to hear.

**Comment by github-user-1** [comment]
Today I was traveling and when checking it seems that SoundWaves did download via mobile connection again - not that much but around another 17 MB (see below). I have set the options to manual download only and to download via WLAN only (see below).

I think SoundWaves was trying to catch new episode lists, podcast covers, etc. while moving around. I had WAN connections from time to time, but also mobile connections. Maybe SoundWaves starts something in WLAN mode but doesn't stop if the WLAN is dropped and the connection moved over to 3G/4G (just an idea)?

![screenshot_2016-12-14-19-59-56](https://cloud.githubusercontent.com/assets/6796538/21197693/49b7020a-c234-11e6-8262-18bd462d8f0b.png)

![screenshot_2016-12-14-20-01-26](https://cloud.githubusercontent.com/assets/6796538/21197699/4d22a642-c234-11e6-9a32-d63fffdd7c39.png)

**Comment by bottiger** [comment]
@github-user-1 I think you are right. SoundWaves should not refresh feeds, and should not fetch album covers  on your case. But all the checks are made before starting a connection, and not while downloading a file. I honestly thought my "download a file" code would just break when the connection type changed, but it may be the case that it handles it and keeps downloading using mobile data. 

I will look into it.

**Comment by github-user-1** [comment]
Just found this information (tap on the app on the data-usage list) - don't know if it's useful or not but wanted to share it at least. It shows the foreground (3 MB) and background (25 MB) traffic consumption:

![screenshot_2016-12-16-18-26-24](https://cloud.githubusercontent.com/assets/6796538/21285538/1ad6ac14-c433-11e6-86ac-4a5877b6c945.jpg)

**Comment by bottiger** [comment]
@github-user-1 Hi again. I need to work a bit more on this. It turns out that loading images takes a bit more bandwidth than I expected and I do not have a good system to handle this yet. The "Download only on wifi" was only meant for downloading entire episodes, but I guess I need to make it into two options. One which is "only download episodes on WiFi" and one which says "not do download anything in the background" on mobile data.

However, it will take a few days to fix properly. Right now I had to revert back to fetching images on mobile data as well because the alternative was to problematic for various reasons.

**Comment by bottiger** [comment]
@github-user-1 I've added a new setting in order to hopefully fix this problem for real. Now there is one settings for only downloading files on wifi, and one settings which will disable all background data (like refreshing feeds) on mobile data.

Hope this helps you.
