### ISSUE TITLE
Can't select .opml file for import

### ISSUE THREAD

**Issue by stkb** [bottiger/SoundWaves#93]
Version 0.148.28.350-google-release, Android 5.1

Hi, just trying this app out and it looks nice. However I can't import my subscriptions from an opml file created from Podcast Addict. I'm trying to import it with the Import OPML function, but after navigating to the file, it's greyed-out and can't be selected for import.

<img width="360" alt="screenshot_2016-12-21-08-59-57" src="https://cloud.githubusercontent.com/assets/6125444/21381809/b36ec754-c75d-11e6-8bd5-4983d30dac73.png">

Tried moving/renaming the file but it still doesn't work.

**Comment by bottiger** [comment]
@stkb I'll look into it ASAP

**Comment by bottiger** [comment]
@stkb I just tested it on my phone and I do not have the same problem. Which file manager are you using (if any)? When you click the import and get a slide in menu - what do you do from there?

**Comment by AugerC** [comment]
Yeah, it happens with the stock file manager, it seems that you have to specify the file extension you want to access. I tried to fix it, but unsuccessfully. 
From now, if you try to select the file with some other file manager than the android stock one, you should be able to select the file.

**Comment by bottiger** [comment]
@stkb I have hopefully fixed the issue and pushed it to the beta version on the play store, which is available here: https://play.google.com/apps/testing/org.bottiger.podcast (Version 0.148.29.351-google-release)

Could you please test it? I would be a great help.

@AugerC  I found that [there is an API which allows for multiple filetypes on KitKat and above](http://stackoverflow.com/questions/1698050/multiple-mime-types-in-android). See this commit: https://github.com/bottiger/SoundWaves/commit/b3700c5b980318a365e756966e37e5001e842ab4

**Comment by stkb** [comment]
Thanks guys, yeah I was the stock file manager to find the file. I also have the Amaze file explorer installed and later I tried going through that to pick the file, and it worked fine.

Unfortunately after updating to the .351 version I'm still seeing the same issue with the stock browser though.

Since this issue is kinda resolved for me you can close it if you wish, although I guess its not ideal, and I can continue helping to diagnose and test fixes too.

**Comment by bottiger** [comment]
@stkb I would love all the feedback I can get. Both functional problems, and bugs.

Also, I found a problem with OPML files from Podcast addict specifically which should be fixed in the master branch now. But since you have solved your issue I'm not going to publish a new version again.

Thanks for your feedback
