### ISSUE TITLE
gPodder should be gpodder.net

### ISSUE THREAD

**Issue by tssva** [bottiger/SoundWaves#98]
gpodder.net is referred to in the app as gPodder and GPodder. The documentation at gpodder.net requests that applications refer to the service as gpodder.net. gPodder should only be used in reference to the gPodder podcast client.

**Comment by bottiger** [comment]
I will look into this. I thought I was careful to get out right, but maybe I didn't :)

**Comment by bottiger** [comment]
Fixed in 2eea54fba47652d455e359afc08135124f165110 . Will be in the next release
